# docker-compose.yml

version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TestDB-Claude
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TestDB-Claude
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: